### ISSUE TITLE
혹시 사용 방법을 알 수 있을까요

### ISSUE THREAD

**Issue by Foreist** [monologg/KoBERT-KorQuAD#1]

**Comment by monologg** [comment]
안녕하세요 아직 미완인 레포지토리이긴 하지만 run_kobert.sh나 run_mbert 스크립트를 bash run하면 됩니다. Multilingual bert의 경우는 문제가 없는데 Kobert의 경우 exact match 값이 너무 낮은 문제가 있어서 현재 수정중에 있습니다.

참고로 해당 코드는 transformers 라이브러리의 example 코드를 가져왔습니다. 추후 리팩토링 예정입니다.
감사합니다:)

**Comment by monologg** [comment]
수정하는데 시간이 좀 걸릴꺼같습니다. 급하신 경우에는 아래의 두 개의 레포를 참조하시면될꺼 같습니다.
- https://github.com/graykode/KorQuAD-beginner
- https://github.com/lyeoni/KorQuAD

**Comment by Foreist** [comment]
친절한 답변 감사합니다. 해당 이슈는 종료하겠습니다!
