### ISSUE TITLE
SKT KoBERT와의 차이점

### ISSUE THREAD

**Issue by HanNayeoniee** [monologg/KoBERT-KorQuAD#4]
안녕하세요 우선 hugging face를 사용해 많은 사람들이 KoBERT를 사용할 수 있도록 깃허브 에 공유해주셔서 감사합니다.

BERT를 공부하고 Question Answering task가 흥미로워서 한국어 데이터셋에 pre-train된 모델을 사용해 KorQuAD 데이터셋으로 fine-tuning하고자 합니다. KoBERT 모델을 찾던 중 monologg님의 KoBERT 저장소를 찾았고, 궁금한점이 있어서 이슈 남깁니다.

저는 SKT의 KoBERT 모델은 기존 구글에서 발표한 BERT모델에 한국어 위키피디아 데이터를 사용해 학습시킨 모델이라고 이해했습니다. (제가 잘못 알고있다면 알려주시면 감사하겠스습니다.) 
그럼 monologg님께서 만든 KoBERT-KorQuAD 레파지토리는 SKT의 KoBERT와 어떤 차이점이 있는지 궁금합니다.

감사합니다.

**Comment by monologg** [comment]
안녕하세요!

정확히는 제가 배포한 [KoBERT-Transformers](https://github.com/monologg/KoBERT-Transformers)와 [원본 SKT KoBERT](https://github.com/SKTBrain/KoBERT)의 차이에서 기인한 문제입니다.

SKT에서 최초에 배포한 KoBERT가 huggingface transformers와 호환이 되지 않는 부분이 있었고, 이러한 불편함을 해소하고자 `KoBERT-Transformers` 라는 라이브러리를 배포하면서 tokenizer 코드를 새로 구현했습니다 (`tokenization_kobert.py` 참고)

자세한 내용은 [KoBERT-Transformers](https://github.com/monologg/KoBERT-Transformers) 참고하시면 될 것 같습니다!

감사합니다:)

**Comment by monologg** [comment]
추가적인 이슈 없으면 닫도록 하겠습니다!
추가적인 궁금증 생기시면 자유롭게 reopen 하면 될 거 같아요:)

**Comment by HanNayeoniee** [comment]
네!!
제가 답변이 늦어서 죄송합니다 이슈 답변 감사합니다!

2021년 6월 15일 (화) 오후 4:18, Jangwon Park ***@***.***>님이 작성:
