### ISSUE TITLE
안녕하세요 질문 드립니다.

### ISSUE THREAD

**Issue by suxxin** [monologg/KoBERT-KorQuAD#5]
![스크린샷 2021-09-02 오전 10 52 56](https://user-images.githubusercontent.com/58119215/131768665-bec1706a-1668-4496-803d-427dd1c54811.png)
안녕하세요 

올려주신 Usage대로 학습 진행시에 마지막에 이렇게 끝나는데 result 가 empty {}로 보입니다 .
혹시 왜그런지 알 수 있을까요? 

제가 준 argument 들은 이렇습니다 

python3 run_squad.py --model_type kobert \
                       --model_name_or_path monologg/kobert \
                       --output_dir output \
                       --data_dir data \
                       --train_file our_train_data.json \
                       --predict_file our_test_data.json \
                       --per_gpu_train_batch_size 8 \
                       --per_gpu_eval_batch_size 8 \
                       --max_seq_length 512 \
                       --logging_steps 4000 \
                       --save_steps 4000 \
                       --do_train

**Comment by minhson-kaist** [comment]
you can simply add option --do_eval and it will gennerate the result.
